# Generated by Django 3.2.7 on 2021-09-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=9)),
                ('image', models.ImageField(default='default.jpg', upload_to='imgofstud/')),
            ],
        ),
        migrations.DeleteModel(
            name='stud',
        ),
    ]
