# Generated by Django 3.2.7 on 2021-09-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>',
            new_name='image',
        ),
    ]
