# Generated by Django 3.2.7 on 2021-09-15 14:04

import Face.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Face', '0002_auto_20210915_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=Face.models.path_and_rename),
        ),
    ]
